name: Publish Release Artifacts

on:
  release:
    types:
      - published
      - edited

permissions:
  contents: read

jobs:
  build-and-publish:
    strategy:
      matrix:
        os: [linux, darwin, windows]
        arch: [amd64, arm64]
    env:
      TOOL_NAME: cleanup-ecr
      OUTPUT_FOLDER: dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
      - name: Build
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: '0' # disable linking of glibc
        run: |
          mkdir -p "./${OUTPUT_FOLDER}"
          go build -C "./cmd/${TOOL_NAME}" -o "$(pwd)/${OUTPUT_FOLDER}/${TOOL_NAME}"
      - uses: thedoctor0/zip-release@0.7.6
        with:
          type: zip
          directory: ${{ env.OUTPUT_FOLDER }}
          path: ${{ env.TOOL_NAME }}
          filename: ${{ env.TOOL_NAME }}-${{ matrix.os }}-${{ matrix.arch }}.zip
          custom: '-9' # highest compression
      - name: Upload Release Artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.event.release.tag_name }}
          BUILT_OS: ${{ matrix.os }}
          BUILT_ARCH: ${{ matrix.arch }}
        run: |
          gh release upload --clobber "${TAG_NAME}" \
            "./${OUTPUT_FOLDER}/${TOOL_NAME}-${BUILT_OS}-${BUILT_ARCH}.zip"
